USE Cadastro;

SELECT * FROM Gafanhotos;

SELECT * FROM Cursos;

/* ORDER BY CLASSIFICA POR ORDEM CRESCENTE (ORDEM ALFABÉTICA) OS REGISTROS*/
SELECT * FROM Cursos ORDER BY Nome;

/* ORDER BY DESC CLASSIFICA POR ORDEM DECRESCENTE (ALFABETO AO CONTRÁRIO) DOS REGISTROS */
SELECT * FROM Cursos ORDER BY Nome DESC;

/* SELECIONANDO COLUNAS ( SELECT nome, carga, ano FROM Cursos ORDER BY Nome; ) */
SELECT Nome, Carga, Ano FROM Cursos ORDER BY Nome;

/* SELECIONANDO LINHAS (SELECT * FROM Cursos WHERE Ano = '2016' ORDER BY Nome; )*/
SELECT * FROM Cursos WHERE Ano = '2016' ORDER BY Nome;

/* SELECIONANDO LINHAS E COLUNAS ( SELECT Nome, Descrição, FROM Cursos WHERE Ano <= '2015' ORDER BY Nome;) */
SELECT Nome , Descricao FROM Cursos WHERE Ano <= '2015' ORDER BY Nome;

/* SELECIONANDO INTERVALOS ( SELECT * FROM Cursos WHERE Totaulas BETWEEN '20' AND '30'; ) BETWEEN SIGNIFICA ENTRE E NELE VC PODE ESPECIFICAR FAIXAS DE VALORES */
SELECT Nome, Ano FROM Cursos WHERE Ano BETWEEN '2014' AND '2016';

/* SELECIONANDO VALORES ( SELECT Idcursos , Nome FROM Cursos WHERE Ano IN ('2014', '2016', '2018') ORDER BY Nome; ) IN SIGNIFICA QUE VC PODE COLOCAR VALORES ESPECÍFICOS. */
 SELECT Nome, Descricao, Ano FROM Cursos WHERE Ano IN (2014, 2016) ORDER BY Ano;
 
 /* COMBINANDO TESTES ( SELECT * FROM Cursos WHERE Carga > 35 AND Totaulas < 30 ORDER BY Nome */
 SELECT Nome, carga, Totaulas FROM Cursos WHERE Carga > 35 AND Totaulas < 30;